### ISSUE TITLE
Difference between Two Histograms Produced

### ISSUE THREAD

**Issue by Rohit-Satyam** [guigolab/bamstats#26]
![chr1_Coverage_cumulativeHistogram](https://user-images.githubusercontent.com/55479480/68542229-6a511100-03d0-11ea-83d6-3a4c2236adec.png)
![chr1_Coverage_histogram](https://user-images.githubusercontent.com/55479480/68542232-6fae5b80-03d0-11ea-924f-7820c43cb5a0.png)

Hi @emi80

I ran Bamststs to calculate coverage. However, I am confused between Two histograms whose axis are labeled the same. By Coverage depth which histogram represents true Vertical Depth(Coverage). What does different scale for % reference  scale  signify.

**Comment by emi80** [comment]
HI @Rohit-Satyam,

I am sorry I cannot help you. I think you used the tool @ http://bamstats.sourceforge.net/ which is not the program in this GitHub repository.

Best,
Emilio

**Comment by Rohit-Satyam** [comment]
I be my pardon. Confused it with the other one you mentioned.
