### ISSUE TITLE
Usage of the command line tool

### ISSUE THREAD

**Issue by tushardave26** [guigolab/bamstats#28]
Hello,

Thank you for the tool.

Unfortunately, I am having trouble using the tool. I clone the repo but I am not able to run it. Can someone please provide examples of how can I use the tool?

Thanks.

Best,
Tushar

**Comment by emi80** [comment]
Hi @tushardave26,
apologies for the late reply.

The best way to get started with the tool is to [install a released version](https://github.com/guigolab/bamstats#install-a-released-version) as explained in the README. You should set the `BIN` environment variable according to your need. For example, to install the Linux 64bit binary in `~/bin`:
```
export VERSION=0.3.5 OS=linux ARCH=x86_64 BIN=~/bin
wget -O - https://github.com/guigolab/bamstats/releases/download/v${VERSION}/bamstats-v${VERSION}-${OS}-${ARCH}.tar.gz | tar xz -C ${BIN} bamstats
```

Best,
Emilio

**Comment by tushardave26** [comment]
Thanks, @emi80 for your response. I will give a shot to the solution that you suggested.
