### ISSUE TITLE
Option -t requires an argument!

### ISSUE THREAD

**Issue by NicMAlexandre** [guigolab/bamstats#29]
Hello,

When trying to run jobs with the GUI I get the error "-t requires an argument".

I have tried specifying a target through the following example of a job:

java -Xmx6g -jar BAMStats-1.25/./BAMStats-GUI-1.25.jar -i X.bam -t ref.chr.bed -o X.out

I have generated the target file as follows:

samtools faidx genome.fasta
cut -f1,2 genome.fasta.fai > genome.size.tab

or 

awk -F'\t' '{print $1"\t0\t"$2}' ../genome.fasta.fai > ref.chr.bed

Any help is appreciated!

**Comment by emi80** [comment]
Hi @nicolasalexandre21,

I am sorry but you are posting in the wrong `bamstats` repository.

I am closing this.

Regards,
Emilio
